const $=s=>document.querySelector(s);const drop=$('#dropzone'),input=$('#fileInput'),results=$('#results');let current=null,report=null;
const TYPES={jpg:'image/jpeg',png:'image/png',webp:'image/webp'};
const bytesToText=(u8,start=0,end=u8.length)=>{let s='';for(let i=start;i<Math.min(end,u8.length);i++)s+=u8[i]>=32&&u8[i]<127?String.fromCharCode(u8[i]):' ';return s};
const human=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
function item(label,detail,kind='private'){return{label,detail,kind}}
function scanJPEG(b){const found=[],kept=[];let p=2;while(p+4<=b.length&&b[p]===255){const marker=b[p+1];if(marker===217||marker===218)break;const len=(b[p+2]<<8)|b[p+3];if(len<2||p+2+len>b.length)break;const text=bytesToText(b,p+4,Math.min(p+4+len,p+520)).toLowerCase();if(marker===225){if(text.includes('exif')){found.push(item('EXIF camera data','Device, capture settings, or timestamps may be present'));kept.push([p,p+2+len,'private'])}else if(text.includes('xmp')){const prov=/c2pa|content.?credential|generative/i.test(text);found.push(item(prov?'Content Credentials reference':'XMP editing data',prov?'A provenance reference was detected':'Editing software or workflow details may be present',prov?'provenance':'private'));kept.push([p,p+2+len,prov?'keep':'private'])}}else if(marker===237){found.push(item('IPTC publishing data','Author, caption, or copyright fields may be present'));kept.push([p,p+2+len,'private'])}else if(marker===254){found.push(item('JPEG comment','A hidden comment field is embedded'));kept.push([p,p+2+len,'private'])}else if(marker===235||text.includes('c2pa')||text.includes('jumb')){found.push(item('C2PA / JUMBF container','Content provenance data detected','provenance'));kept.push([p,p+2+len,'keep'])}p+=2+len}return{found,ranges:kept,clean:()=>removeRanges(b,kept.filter(x=>x[2]==='private'))}}
function removeRanges(b,ranges){if(!ranges.length)return b.slice();const out=[];let p=0;for(const [s,e] of ranges.sort((a,z)=>a[0]-z[0])){out.push(b.slice(p,s));p=e}out.push(b.slice(p));const len=out.reduce((n,x)=>n+x.length,0),r=new Uint8Array(len);let o=0;out.forEach(x=>{r.set(x,o);o+=x.length});return r}
function read32(b,p,little=false){return little?(b[p]|b[p+1]<<8|b[p+2]<<16|b[p+3]<<24)>>>0:(b[p]*16777216+(b[p+1]<<16)+(b[p+2]<<8)+b[p+3])>>>0}
function scanPNG(b){const found=[],remove=[];let p=8;while(p+12<=b.length){const len=read32(b,p),type=bytesToText(b,p+4,p+8),end=p+12+len;if(end>b.length)break;const txt=bytesToText(b,p+8,Math.min(p+8+len,p+520)).toLowerCase();if(type==='eXIf'){found.push(item('EXIF image data','Device, capture settings, or location may be present'));remove.push([p,end])}else if(['tEXt','zTXt','iTXt','tIME'].includes(type)){const prov=/c2pa|content.?credential|generative/i.test(txt);found.push(item(prov?'Content Credentials reference':'PNG text metadata',prov?'A provenance reference was detected':'Comments, software, or timestamps may be present',prov?'provenance':'private'));if(!prov)remove.push([p,end])}p=end;if(type==='IEND')break}return{found,ranges:remove,clean:()=>removeRanges(b,remove)}}
function scanWebP(b){const found=[],chunks=[];let p=12;while(p+8<=b.length){const type=bytesToText(b,p,p+4),len=read32(b,p+4,true),end=p+8+len+(len%2);if(end>b.length)break;const txt=bytesToText(b,p+8,Math.min(p+8+len,p+520)).toLowerCase();if(type==='EXIF'){found.push(item('EXIF image data','Device, capture settings, or location may be present'));chunks.push([p,end])}else if(type==='XMP '){const prov=/c2pa|content.?credential|generative/i.test(txt);found.push(item(prov?'Content Credentials reference':'XMP editing data',prov?'A provenance reference was detected':'Editing software or workflow details may be present',prov?'provenance':'private'));if(!prov)chunks.push([p,end])}p=end}return{found,ranges:chunks,clean:()=>{const r=removeRanges(b,chunks);const size=r.length-8;r[4]=size&255;r[5]=(size>>>8)&255;r[6]=(size>>>16)&255;r[7]=(size>>>24)&255;return r}}}
function scan(b,type){let data;if(type===TYPES.jpg&&b[0]===255&&b[1]===216)data=scanJPEG(b);else if(type===TYPES.png&&bytesToText(b,1,4)==='PNG')data=scanPNG(b);else if(type===TYPES.webp&&bytesToText(b,0,4)==='RIFF'&&bytesToText(b,8,12)==='WEBP')data=scanWebP(b);else throw new Error('This file format is not supported yet.');const lower=bytesToText(b,0,Math.min(b.length,1000000)).toLowerCase();if(/gpslatitude|gpslongitude|location/.test(lower)&&!data.found.some(x=>x.label.includes('Location')))data.found.unshift(item('Location reference','GPS or location-related data detected'));if(/photoshop|lightroom|gimp|capture one/.test(lower))data.found.push(item('Editing software','An editor name is embedded in the file'));return data}
function renderList(el,items,empty){el.innerHTML='';if(!items.length)items=[{label:empty,detail:'Nothing in this category was detected',kind:'safe'}];items.forEach(x=>{const d=document.createElement('div');d.className='finding-item '+(x.kind==='safe'?'safe':'');d.innerHTML=`<span class="finding-icon">${x.kind==='safe'?'✓':'!'}</span><div><p>${escapeHTML(x.label)}</p><small>${escapeHTML(x.detail)}</small></div><span class="badge">${x.kind==='safe'?'Clear':'Found'}</span>`;el.appendChild(d)})}
const escapeHTML=s=>s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function handle(file){if(!file)return;if(!Object.values(TYPES).includes(file.type)){toast('Choose a JPEG, PNG, or WebP image');return}try{const b=new Uint8Array(await file.arrayBuffer());report=scan(b,file.type);current={file,b};const img=$('#preview');if(img.src)URL.revokeObjectURL(img.src);img.src=URL.createObjectURL(file);$('#fileName').textContent=file.name;$('#fileDetails').textContent=`${human(file.size)} · ${file.type.replace('image/','').toUpperCase()}`;const priv=report.found.filter(x=>x.kind==='private'),prov=report.found.filter(x=>x.kind==='provenance');renderList($('#privacyFindings'),priv,'No private metadata');renderList($('#provenanceFindings'),prov,'No container credentials');$('#privacyCount').textContent=priv.length?`${priv.length} FOUND`:'CLEAR';$('#provCount').textContent=prov.length?`${prov.length} FOUND`:'CLEAR';const score=Math.max(24,100-priv.length*19);$('#score').textContent=score;$('#scoreRing').style.background=`conic-gradient(${score>75?'var(--acid)':score>45?'var(--amber)':'var(--red)'} ${score*3.6}deg,#293032 0deg)`;$('#summaryTitle').textContent=priv.length?`${priv.length} private ${priv.length===1?'detail':'details'} detected`:'No private metadata detected';$('#summaryCopy').textContent=prov.length?'Provenance is listed separately and will not be targeted.':'The file is ready to share or verify below.';$('#cleanDescription').textContent=priv.length?'Private container metadata will be removed. Image pixels stay unchanged.':'No removable private metadata was found; you can still export a verified copy.';results.hidden=false;$('.workspace').hidden=true;results.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){toast(e.message||'Could not scan that file')}}
function clean(){if(!current||!report)return;const cleaned=report.clean(),blob=new Blob([cleaned],{type:current.file.type}),a=document.createElement('a'),base=current.file.name.replace(/\.[^.]+$/,'');a.href=URL.createObjectURL(blob);a.download=`${base}-clean.${current.file.name.split('.').pop()}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast(`Clean copy ready · ${human(cleaned.length)}`)}
function reset(){current=report=null;input.value='';results.hidden=true;$('.workspace').hidden=false;window.scrollTo({top:0,behavior:'smooth'})}function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2800)}
$('#browseBtn').onclick=e=>{e.stopPropagation();input.click()};drop.onclick=e=>{if(e.target.tagName!=='BUTTON')input.click()};drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}};input.onchange=()=>handle(input.files[0]);['dragenter','dragover'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop.ondrop=e=>handle(e.dataTransfer.files[0]);$('#cleanBtn').onclick=clean;$('#startOver').onclick=reset;
try{const ctx=document.modelContext;if(ctx?.registerTool){ctx.registerTool({name:'open_image_picker',title:'Choose image',description:'Open the device file picker to select an image for a local metadata scan.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(){input.click();return{status:'picker_opened'}}});ctx.registerTool({name:'get_scan_summary',title:'Read scan summary',description:'Return the visible metadata scan summary for the currently selected image.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){if(!current)throw new Error('No image is currently selected');return{file:current.file.name,privacy_findings:report.found.filter(x=>x.kind==='private').map(x=>x.label),provenance_findings:report.found.filter(x=>x.kind==='provenance').map(x=>x.label)}}})}}catch(e){}
